spring:
  application:
    name: his-cloud-eureka
  zipkin:
    base-url: http://192.168.0.164:10014
  boot:
    admin:
      client:
        url: http://192.168.0.164:10013

server:
  port: 10030

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
    endpoint:
      health:
        show-details: ALWAYS   #health endpoint是否必须显示全部细节

eureka:
  instance:
    prefer-ip-address: true
    hostname: 192.168.0.164
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


